version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-security:
        dependency-type: production
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
