import type { PayrollFeature } from "@/components/landing/PayrollFeaturePage";

const PAYROLL_SOURCES = [
  {
    name: "URSSAF / Mon-entreprise",
    detail: "Modèle social Publicodes utilisé par RH Pilot pour le calcul social.",
    href: "https://mon-entreprise.urssaf.fr/",
  },
  {
    name: "BOSS",
    detail: "Bulletin officiel de la sécurité sociale et doctrine administrative.",
    href: "https://boss.gouv.fr/",
  },
  {
    name: "impots.gouv.fr — DGFiP",
    detail: "Prélèvement à la source et obligations fiscales déclaratives.",
    href: "https://www.impots.gouv.fr/",
  },
  {
    name: "Légifrance",
    detail: "Code du travail et textes législatifs et réglementaires.",
    href: "https://www.legifrance.gouv.fr/",
  },
  {
    name: "Service-Public.fr",
    detail: "Informations administratives officielles pour employeurs et salariés.",
    href: "https://www.service-public.fr/",
  },
];

const COMMON_DETAILS = [
  "Le calcul social repose sur le modèle Publicodes de Mon-entreprise, maintenu par l’Urssaf.",
  "RH Pilot conserve la version du modèle et les paramètres utilisés pour produire le résultat.",
  "Les références réglementaires sont identifiables : URSSAF, BOSS, DGFiP, Légifrance et Service-Public.fr.",
  "Lorsqu’un traitement ne peut pas être déterminé avec suffisamment de certitude, RH Pilot ne fabrique pas un résultat.",
];

export const PAYROLL_FEATURES: Record<string, PayrollFeature> = {
  production: {
    eyebrow: "Production de la paie",
    title: "Préparer une paie, c’est d’abord savoir ce qui doit être contrôlé.",
    intro: "RH Pilot rassemble les données de la période, calcule à partir du moteur social de Mon-entreprise et garde la trace des éléments qui ont servi au résultat.",
    image: "https://images.unsplash.com/photo-1758876201660-103984519266?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnelle consultant un document dans un bureau",
    imagePosition: "right",
    visualKicker: "Période de paie",
    visualTitle: "Du dossier salarié au bulletin, sans boîte noire.",
    visualText: "Une période de paie réunit plusieurs contrôles : les données disponibles, les variables du mois, les événements RH et les paramètres qui conditionnent le calcul. RH Pilot organise ce passage avant la validation.",
    points: [
      { title: "Préparer", text: "Les informations indispensables du salarié et de l’entreprise sont réunies avant le calcul." },
      { title: "Calculer", text: "Le moteur social Publicodes produit les montants à partir des données et règles disponibles." },
      { title: "Revoir", text: "Le résultat et les points de contrôle restent visibles avant validation et édition." },
    ],
    workflowTitle: "Une période se clôture en plusieurs temps",
    workflow: [
      { label: "Préparation", text: "Données salarié, entreprise, variables et événements du mois." },
      { label: "Calcul", text: "Application du modèle social disponible dans RH Pilot." },
      { label: "Contrôle", text: "Lecture du résultat et des éléments qui nécessitent une vérification." },
      { label: "Validation", text: "La période est validée avant de préparer les bulletins." },
    ],
    detailsTitle: "Les références du traitement",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Le moteur de calcul et les références documentaires ne sont pas confondus : Publicodes calcule, tandis que les sources officielles permettent de cadrer et de documenter le traitement.",
  },
  variables: {
    eyebrow: "Variables de paie",
    title: "Les éléments du mois doivent arriver au bon endroit.",
    intro: "Heures, primes, absences et autres variables sont rattachées à une période et à un salarié. RH Pilot les prépare avant le calcul pour qu’elles puissent être relues.",
    image: "https://images.unsplash.com/photo-1758876020300-76a782ca51c6?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnel vérifiant des documents et des graphiques",
    imagePosition: "left",
    visualKicker: "Variables mensuelles",
    visualTitle: "Avant le montant, il y a la donnée.",
    visualText: "Une variable oubliée ou rattachée au mauvais salarié suffit à perturber une période. La préparation doit donc être aussi lisible que le calcul lui-même.",
    points: [
      { title: "Collecter", text: "Les éléments variables du mois sont réunis pour la période concernée." },
      { title: "Rattacher", text: "Chaque donnée est liée au salarié et au cycle de paie auquel elle appartient." },
      { title: "Vérifier", text: "Les informations sont contrôlées avant qu’elles n’alimentent le calcul social." },
    ],
    workflowTitle: "Une variable suit son propre chemin",
    workflow: [
      { label: "Collecter", text: "Réunir les éléments du mois auprès des bonnes personnes." },
      { label: "Rattacher", text: "Associer chaque élément au salarié et à la période concernés." },
      { label: "Contrôler", text: "Repérer les incohérences ou les informations encore manquantes." },
      { label: "Calculer", text: "Intégrer les variables validées au traitement de la période." },
    ],
    detailsTitle: "Un traitement documenté",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "RH Pilot ne présente pas une variable comme une règle de paie. La donnée est préparée dans l’outil, puis le calcul social est confié au moteur prévu pour cette tâche.",
  },
  absences: {
    eyebrow: "Congés & absences",
    title: "Une absence doit rester liée à la période de paie qu’elle affecte.",
    intro: "Congés et absences vivent dans le dossier RH, mais peuvent aussi avoir un effet sur la paie. RH Pilot conserve ce lien et recherche le traitement applicable avant d’intégrer un impact.",
    image: "https://images.unsplash.com/photo-1762341116197-fb94a4f37173?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnelle consultant un planning dans un bureau",
    visualKicker: "Temps de travail",
    visualTitle: "Le calendrier RH ne s’arrête pas au calendrier.",
    visualText: "Une absence concerne des dates, un salarié, un contexte de travail et parfois des règles collectives. C’est l’ensemble qui doit être regardé avant de modifier une période de paie.",
    points: [
      { title: "Enregistrer", text: "L’absence reste rattachée au salarié et aux dates concernées." },
      { title: "Identifier le traitement", text: "Le type d’absence, la convention collective et les règles applicables conditionnent le traitement." },
      { title: "Ne pas extrapoler", text: "Lorsqu’une règle exploitable n’est pas disponible, RH Pilot signale le blocage au lieu d’estimer." },
    ],
    workflowTitle: "Du calendrier au traitement de paie",
    workflow: [
      { label: "Enregistrer", text: "Date, salarié et événement sont conservés dans le dossier concerné." },
      { label: "Qualifier", text: "Le traitement applicable est recherché à partir des informations disponibles." },
      { label: "Calculer", text: "Un impact est intégré uniquement lorsqu’une règle valide permet de le déterminer." },
      { label: "Contrôler", text: "L’impact reste visible avant la validation de la période." },
    ],
    detailsTitle: "Cadre juridique et social",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Pour les congés et absences, le droit applicable peut dépendre du Code du travail, des règles collectives et de la situation du salarié. L’outil doit aussi savoir reconnaître les cas qu’il ne peut pas calculer.",
  },
  arrets: {
    eyebrow: "Arrêts de travail",
    title: "Un arrêt de travail ne se résume pas à une date à saisir.",
    intro: "L’arrêt doit être relié au salarié, à sa période, aux informations utiles et au traitement applicable. RH Pilot structure cette vérification sans transformer une situation incomplète en montant arbitraire.",
    image: "https://images.unsplash.com/photo-1770048532712-4fde5ef7eb90?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnel travaillant dans un bureau contemporain",
    imagePosition: "left",
    visualKicker: "Événement salarié",
    visualTitle: "Relier l’événement, la règle et le résultat.",
    visualText: "Les arrêts de travail peuvent mobiliser plusieurs règles et plusieurs sources. Le rôle de RH Pilot est de rendre le traitement compréhensible et de faire apparaître les informations qui conditionnent le calcul.",
    points: [
      { title: "Documenter", text: "Les dates et informations utiles sont regroupées autour du salarié concerné." },
      { title: "Vérifier", text: "Le traitement dépend des données nécessaires et des règles applicables au dossier." },
      { title: "Contrôler", text: "L’impact calculé reste soumis à une revue avant validation de la paie." },
    ],
    workflowTitle: "Un arrêt passe par le dossier avant le calcul",
    workflow: [
      { label: "Signaler", text: "L’événement et ses dates sont enregistrés dans le dossier salarié." },
      { label: "Compléter", text: "Les informations nécessaires au traitement sont réunies." },
      { label: "Traiter", text: "Le moteur applique le traitement disponible pour la situation concernée." },
      { label: "Revoir", text: "L’impact sur la période est présenté avant la validation." },
    ],
    detailsTitle: "Des références identifiables",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Légifrance et Service-Public.fr documentent le cadre juridique ; le calcul social opérationnel de RH Pilot reste, lui, rattaché au modèle Publicodes utilisé par Mon-entreprise.",
  },
};
