import type { PayrollFeature } from "@/components/landing/PayrollFeaturePage";

const PAYROLL_SOURCES = [
  {
    name: "URSSAF / Mon-entreprise",
    detail: "Règles officielles utilisées pour les calculs sociaux.",
    href: "https://mon-entreprise.urssaf.fr/",
  },
  {
    name: "BOSS",
    detail: "Bulletin officiel de la sécurité sociale.",
    href: "https://boss.gouv.fr/",
  },
  {
    name: "impots.gouv.fr — DGFiP",
    detail: "Prélèvement à la source et obligations fiscales.",
    href: "https://www.impots.gouv.fr/",
  },
  {
    name: "Légifrance",
    detail: "Code du travail et textes législatifs et réglementaires.",
    href: "https://www.legifrance.gouv.fr/",
  },
  {
    name: "Service-Public.fr",
    detail: "Informations administratives officielles.",
    href: "https://www.service-public.fr/",
  },
];

const COMMON_DETAILS = [
  "Le calcul de la paie s’appuie sur des règles sociales officielles.",
  "RH Pilot garde les informations importantes utilisées pour calculer chaque période.",
  "Les références utilisées sont accessibles : URSSAF, BOSS, DGFiP, Légifrance et Service-Public.fr.",
  "Lorsqu’une information manque pour déterminer un traitement, RH Pilot ne produit pas de montant incomplet.",
];

export const PAYROLL_FEATURES: Record<string, PayrollFeature> = {
  production: {
    eyebrow: "Production de la paie",
    title: "Préparer une paie, c’est d’abord savoir ce qui doit être contrôlé.",
    intro: "RH Pilot rassemble les informations du mois, calcule la paie et garde une trace des données utilisées pour obtenir le résultat.",
    image: "https://images.unsplash.com/photo-1758876201660-103984519266?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnelle consultant un document dans un bureau",
    imagePosition: "right",
    visualKicker: "Période de paie",
    visualTitle: "Du dossier salarié au bulletin.",
    visualText: "Une période de paie réunit les informations du salarié, les éléments du mois et les événements RH. RH Pilot les présente au même endroit avant la validation.",
    points: [
      { title: "Préparer", text: "Les informations nécessaires du salarié et de l’entreprise sont réunies avant le calcul." },
      { title: "Calculer", text: "RH Pilot calcule les montants à partir des informations disponibles." },
      { title: "Contrôler", text: "Le résultat peut être relu et vérifié avant validation et édition du bulletin." },
    ],
    workflowTitle: "Les étapes d’une période de paie",
    workflow: [
      { label: "Préparer", text: "Réunir les informations du salarié, de l’entreprise et du mois." },
      { label: "Calculer", text: "Calculer les différents montants de la paie." },
      { label: "Contrôler", text: "Vérifier le résultat et les informations qui demandent une attention." },
      { label: "Valider", text: "Valider la période avant de préparer les bulletins." },
    ],
    detailsTitle: "Références utilisées",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Le calcul repose sur des règles sociales officielles. Les autres sources servent à retrouver les textes et informations utiles.",
  },
  variables: {
    eyebrow: "Variables de paie",
    title: "Les éléments du mois doivent être rattachés à la bonne période.",
    intro: "Heures, primes, absences et autres éléments du mois sont rattachés au bon salarié avant d’être pris en compte dans la paie.",
    image: "https://images.unsplash.com/photo-1758876020300-76a782ca51c6?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnel vérifiant des documents et des graphiques",
    imagePosition: "left",
    visualKicker: "Variables mensuelles",
    visualTitle: "Avant le calcul, vérifier la donnée.",
    visualText: "Une donnée doit correspondre au bon salarié et au bon mois. RH Pilot permet de la vérifier avant de l’intégrer à la paie.",
    points: [
      { title: "Collecter", text: "Les éléments du mois sont réunis pour la période concernée." },
      { title: "Rattacher", text: "Chaque élément est associé au bon salarié et au bon mois." },
      { title: "Vérifier", text: "Les informations sont contrôlées avant leur prise en compte dans la paie." },
    ],
    workflowTitle: "Le traitement des variables",
    workflow: [
      { label: "Collecter", text: "Réunir les éléments du mois." },
      { label: "Associer", text: "Les relier au bon salarié et au bon mois." },
      { label: "Contrôler", text: "Repérer les informations manquantes ou incohérentes." },
      { label: "Calculer", text: "Prendre en compte les éléments vérifiés dans la paie." },
    ],
    detailsTitle: "Références utilisées",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Les variables sont enregistrées dans RH Pilot puis prises en compte dans le calcul de la période.",
  },
  absences: {
    eyebrow: "Congés & absences",
    title: "Une absence doit être prise en compte sur la période concernée.",
    intro: "Les congés et absences sont enregistrés avec leurs dates. Lorsqu’ils ont un effet sur la paie, RH Pilot vérifie le traitement à appliquer.",
    image: "https://images.unsplash.com/photo-1762341116197-fb94a4f37173?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnelle consultant un planning dans un bureau",
    visualKicker: "Temps de travail",
    visualTitle: "Relier les dates au traitement de paie.",
    visualText: "Le traitement d’une absence dépend des dates et de sa nature. Ces informations sont réunies avant de déterminer son effet sur la paie.",
    points: [
      { title: "Enregistrer", text: "L’absence est rattachée au salarié et aux dates concernées." },
      { title: "Vérifier", text: "Le type d’absence et les informations nécessaires sont contrôlés." },
      { title: "Contrôler", text: "L’effet sur la paie est visible avant la validation de la période." },
    ],
    workflowTitle: "De l’absence à la paie",
    workflow: [
      { label: "Enregistrer", text: "Conserver les dates et l’événement dans le dossier du salarié." },
      { label: "Vérifier", text: "Réunir les informations nécessaires au traitement." },
      { label: "Calculer", text: "Prendre en compte l’absence lorsqu’un traitement est disponible." },
      { label: "Contrôler", text: "Vérifier son effet avant de valider la période." },
    ],
    detailsTitle: "Références utilisées",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Le traitement dépend des informations du dossier et des règles applicables à la situation.",
  },
  arrets: {
    eyebrow: "Arrêts de travail",
    title: "Un arrêt de travail doit être enregistré avant d’être traité en paie.",
    intro: "L’arrêt est rattaché au salarié et à la période concernée. RH Pilot réunit les informations nécessaires avant de calculer la paie.",
    image: "https://images.unsplash.com/photo-1770048532712-4fde5ef7eb90?auto=format&fit=crop&fm=jpg&q=82&w=2400",
    imageAlt: "Professionnel travaillant dans un bureau contemporain",
    imagePosition: "left",
    visualKicker: "Événement salarié",
    visualTitle: "Les dates, les règles et leur impact.",
    visualText: "Un arrêt peut demander plusieurs informations. RH Pilot les rassemble avant de déterminer son effet sur la période de paie.",
    points: [
      { title: "Enregistrer", text: "Les dates et informations utiles sont regroupées dans le dossier salarié." },
      { title: "Vérifier", text: "Les données nécessaires au traitement sont contrôlées." },
      { title: "Contrôler", text: "L’effet sur la paie est présenté avant la validation." },
    ],
    workflowTitle: "Le traitement d’un arrêt",
    workflow: [
      { label: "Enregistrer", text: "L’événement et ses dates sont conservés dans le dossier salarié." },
      { label: "Compléter", text: "Les informations nécessaires sont réunies." },
      { label: "Traiter", text: "Le traitement disponible est appliqué à la période." },
      { label: "Contrôler", text: "L’effet sur la paie est vérifié avant validation." },
    ],
    detailsTitle: "Références utilisées",
    details: COMMON_DETAILS,
    sources: PAYROLL_SOURCES,
    note: "Le traitement dépend des informations disponibles et des règles applicables à la situation concernée.",
  },
};
