import Link from "next/link";
import { ArrowRight, Building2, Check, FileCheck2, FileText, HeartPulse, History, Landmark, LockKeyhole, Scale, ShieldCheck, UserRound } from "lucide-react";
import { MarketingHeader } from "@/components/landing/MarketingHeader";
import { MarketingFooter } from "@/components/landing/MarketingFooter";
import { Reveal } from "@/components/landing/Reveal";
import { PAYROLL_CAPABILITIES, type PayrollCapability } from "./payrollCapabilities";

const iconByKey = { agreement: Scale, health: HeartPulse, contributions: Landmark, netSocial: FileCheck2, payslip: FileText, traceability: History, profile: UserRound, employer: Building2 } as const;

function Sources({ feature }: { feature: PayrollCapability }) {
  if (!feature.sources) return null;
  return <section className="border-t border-surface-border bg-surface-subtle"><div className="mx-auto max-w-6xl px-6 py-16 sm:py-20"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-primary">Références</p><h2 className="mt-3 text-2xl font-semibold text-ink">Sources utilisées</h2></div><div className="grid gap-4 sm:grid-cols-2">{feature.sources.map((source)=><a key={source.name} href={source.href} target="_blank" rel="noreferrer" className="border-t border-surface-border pt-4 hover:border-brand-primary/50"><p className="font-semibold text-ink">{source.name}</p><p className="mt-1 text-sm leading-6 text-ink-soft">{source.detail}</p></a>)}</div></div></div></section>;
}

function AgreementLayout({ feature }: { feature: PayrollCapability }) {
  return <><section className="bg-[#14151A] text-white"><div className="mx-auto max-w-7xl px-6 pb-20 pt-16 sm:pb-28 sm:pt-24"><Reveal variant="left"><p className="text-sm font-semibold text-[#E8432E]">{feature.eyebrow}</p><div className="mt-6 grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-end"><div><h1 className="max-w-4xl text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">{feature.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{feature.intro}</p></div><div className="border border-white/10 bg-white/[.04] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/40">Référentiel</p><div className="mt-6 grid gap-4"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-sm text-white/55">Convention</span><span className="font-medium">Profil salarié</span></div><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-sm text-white/55">Version</span><span className="font-medium">Validée</span></div><div className="flex items-center justify-between"><span className="text-sm text-white/55">Date</span><span className="font-medium">Période de paie</span></div></div></div></div></Reveal></div></section><section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid gap-0 border-y border-surface-border md:grid-cols-2">{feature.points.map((point,index)=><article key={point.label} className={`border-b border-surface-border p-7 md:p-9 ${index % 2 === 0 ? "md:border-r" : ""} ${index >= 2 ? "md:border-b-0" : ""}`}><span className="text-xs font-semibold text-brand-primary">0{index+1}</span><h2 className="mt-4 text-lg font-semibold text-ink">{point.label}</h2><p className="mt-2 text-sm leading-6 text-ink-soft">{point.text}</p></article>)}</div><p className="mt-12 max-w-3xl text-base leading-7 text-ink-soft">{feature.summary}</p></section></>;
}

function HealthLayout({ feature }: { feature: PayrollCapability }) {
  return <><section className="mx-auto max-w-6xl px-6 pb-16 pt-14 sm:pb-24 sm:pt-20"><Reveal variant="left"><p className="text-sm font-semibold text-brand-primary">{feature.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1] tracking-tight text-ink sm:text-6xl">{feature.title}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-ink-soft">{feature.intro}</p></Reveal><Reveal variant="scale" delay={100}><div className="mt-14 overflow-hidden border border-surface-border bg-surface-subtle"><div className="grid lg:grid-cols-[.95fr,1.05fr]"><div className="flex min-h-[360px] flex-col justify-between bg-[#f1f4f7] p-8 sm:p-10"><div><HeartPulse size={32} className="text-brand-primary"/><p className="mt-8 text-sm font-semibold uppercase tracking-[.12em] text-ink-faint">Complémentaire santé</p><p className="mt-3 text-4xl font-semibold tracking-tight text-ink">Paramètres de santé</p></div><div className="grid grid-cols-2 gap-4"><div className="border border-surface-border bg-white p-4"><p className="text-xs text-ink-faint">Montant</p><p className="mt-2 font-semibold text-ink">Mensuel</p></div><div className="border border-surface-border bg-white p-4"><p className="text-xs text-ink-faint">Part employeur</p><p className="mt-2 font-semibold text-ink">50–100 %</p></div></div></div><div className="bg-white p-8 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-primary">Dans le calcul social</p><p className="mt-5 text-lg leading-8 text-ink-soft">{feature.summary}</p><div className="mt-10 space-y-6">{feature.points.map((point,index)=><div key={point.label} className="flex gap-4"><span className="mt-1 text-xs font-semibold text-brand-primary">0{index+1}</span><div><p className="font-semibold text-ink">{point.label}</p><p className="mt-1 text-sm leading-6 text-ink-soft">{point.text}</p></div></div>)}</div></div></div></div></Reveal></section></>;
}

function ContributionsLayout({ feature }: { feature: PayrollCapability }) {
  return <><section className="border-b border-surface-border bg-white"><div className="mx-auto max-w-6xl px-6 pb-16 pt-14 sm:pb-20 sm:pt-20"><div className="flex items-end justify-between gap-8"><div><p className="text-sm font-semibold text-brand-primary">{feature.eyebrow}</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-none tracking-tight text-ink sm:text-6xl">{feature.title}</h1></div><ShieldCheck className="hidden shrink-0 text-brand-primary sm:block" size={34}/></div><p className="mt-7 max-w-2xl text-lg leading-8 text-ink-soft">{feature.intro}</p></div></section><section className="mx-auto max-w-6xl px-6 py-16 sm:py-24"><div className="overflow-hidden border border-surface-border"><div className="grid grid-cols-[1fr,1fr] border-b border-surface-border bg-surface-subtle text-xs font-semibold uppercase tracking-[.12em] text-ink-faint sm:grid-cols-[1.2fr,.8fr]"><div className="px-5 py-4">Poste de cotisation</div><div className="px-5 py-4">Traitement</div></div>{feature.points.map((row,index)=><div key={row.label} className="grid grid-cols-[1fr,1fr] border-b border-surface-border last:border-b-0 sm:grid-cols-[1.2fr,.8fr]"><div className="p-5"><p className="font-semibold text-ink">{row.label}</p><p className="mt-1 text-sm leading-6 text-ink-soft">{row.text}</p></div><div className="flex items-center gap-2 p-5 text-sm text-ink-soft"><span className="text-xs font-semibold text-brand-primary">0{index+1}</span>{index===0?"Part salarié":index===1?"Part employeur":index===2?"Selon présence":"Règle Publicodes"}</div></div>)}</div><div className="mt-12 border-l-2 border-brand-primary/20 pl-6"><p className="text-lg leading-8 text-ink-soft">{feature.summary}</p></div></section></>;
}

function NetSocialLayout({ feature }: { feature: PayrollCapability }) { const labels=["Brut","Cotisations","Net avant impôt","Montant net social"]; return <><section className="bg-[#14151A] text-white"><div className="mx-auto max-w-6xl px-6 pb-20 pt-16 sm:pb-24 sm:pt-24"><Reveal variant="scale"><p className="text-sm font-semibold text-[#E8432E]">{feature.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl">{feature.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{feature.intro}</p></Reveal></div></section><section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid gap-4 md:grid-cols-4">{labels.map((label,index)=><div key={label} className="relative border border-surface-border bg-white p-6"><span className="text-xs font-semibold text-brand-primary">0{index+1}</span><p className="mt-10 text-xl font-semibold text-ink">{label}</p><p className="mt-3 text-sm leading-6 text-ink-soft">{feature.points[index].text}</p>{index<labels.length-1&&<ArrowRight className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 bg-white text-ink-soft md:block" size={20}/>}</div>)}</div><p className="mt-14 max-w-3xl text-lg leading-8 text-ink-soft">{feature.summary}</p></section></>;
}

function PayslipLayout({ feature }: { feature: PayrollCapability }) { return <><section className="mx-auto max-w-6xl px-6 pb-14 pt-14 sm:pb-20 sm:pt-20"><div className="grid gap-12 lg:grid-cols-[.8fr,1.2fr] lg:items-center"><Reveal variant="left"><p className="text-sm font-semibold text-brand-primary">{feature.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-tight text-ink sm:text-6xl">{feature.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink-soft">{feature.intro}</p></Reveal><Reveal variant="right"><div className="mx-auto max-w-md rotate-[-2deg] border border-surface-border bg-white p-4 shadow-[0_24px_80px_-40px_rgba(20,21,26,.35)]"><div className="border border-surface-border p-6"><div className="flex items-center justify-between border-b border-surface-border pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-ink-faint">Bulletin de paie</p><p className="mt-1 font-semibold text-ink">Période verrouillée</p></div><LockKeyhole size={20} className="text-brand-primary"/></div><div className="mt-6 space-y-4">{feature.points.map((point)=><div key={point.label} className="flex items-start gap-3"><Check size={16} className="mt-0.5 shrink-0 text-brand-primary"/><div><p className="text-sm font-semibold text-ink">{point.label}</p><p className="mt-1 text-xs leading-5 text-ink-soft">{point.text}</p></div></div>)}</div></div></div></Reveal></div></section><section className="border-y border-surface-border bg-surface-subtle"><div className="mx-auto max-w-6xl px-6 py-16 sm:py-20"><p className="max-w-2xl text-lg leading-8 text-ink-soft">{feature.summary}</p></div></section></>;
}

function TraceabilityLayout({ feature }: { feature: PayrollCapability }) { return <><section className="mx-auto max-w-6xl px-6 pb-16 pt-14 sm:pb-24 sm:pt-20"><Reveal variant="left"><p className="text-sm font-semibold text-brand-primary">{feature.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-none tracking-tight text-ink sm:text-6xl">{feature.title}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-ink-soft">{feature.intro}</p></Reveal></section><section className="border-y border-surface-border bg-[#f7f8fa]"><div className="mx-auto max-w-6xl px-6 py-16 sm:py-20"><div className="ml-3 border-l border-surface-border pl-8 sm:ml-10 sm:pl-10">{feature.points.map((point,index)=><div key={point.label} className="relative border-b border-surface-border py-8 last:border-b-0"><span className="absolute -left-[46px] top-8 flex h-7 w-7 items-center justify-center rounded-full border border-surface-border bg-white text-[10px] font-semibold text-brand-primary sm:-left-[54px]">0{index+1}</span><p className="text-lg font-semibold text-ink">{point.label}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-soft">{point.text}</p></div>)}</div><div className="mt-12 max-w-3xl border border-surface-border bg-white p-6"><p className="text-base leading-7 text-ink-soft">{feature.summary}</p></div></div></section></>;
}

function ProfileLayout({ feature }: { feature: PayrollCapability }) { return <><section className="bg-surface-subtle"><div className="mx-auto max-w-6xl px-6 pb-16 pt-14 sm:pb-24 sm:pt-20"><div className="flex flex-col gap-12 lg:flex-row lg:items-end lg:justify-between"><Reveal variant="left"><p className="text-sm font-semibold text-brand-primary">{feature.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.98] tracking-tight text-ink sm:text-6xl">{feature.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink-soft">{feature.intro}</p></Reveal><div className="w-full max-w-sm border border-surface-border bg-white p-6 sm:p-7"><div className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-brand-primary/10 text-brand-primary"><UserRound size={20}/></span><div><p className="text-sm font-semibold text-ink">Profil salarié</p><p className="text-xs text-ink-faint">Contexte paie</p></div></div><div className="mt-6 divide-y divide-surface-border">{["Salaire brut","Durée mensuelle","Contrat","Convention"].map((item)=><div key={item} className="flex items-center justify-between py-3 text-sm"><span className="text-ink-soft">{item}</span><span className="font-medium text-ink">Renseigné</span></div>)}</div></div></div></div></section><section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid gap-5 sm:grid-cols-2">{feature.points.map((point,index)=><article key={point.label} className="border border-surface-border p-7"><span className="text-xs font-semibold text-brand-primary">0{index+1}</span><h2 className="mt-4 text-lg font-semibold text-ink">{point.label}</h2><p className="mt-2 text-sm leading-6 text-ink-soft">{point.text}</p></article>)}</div><p className="mt-12 max-w-3xl text-lg leading-8 text-ink-soft">{feature.summary}</p></section></>;
}

function EmployerLayout({ feature }: { feature: PayrollCapability }) { return <><section className="bg-[#14151A] text-white"><div className="mx-auto max-w-7xl px-6 pb-20 pt-16 sm:pb-24 sm:pt-24"><div className="grid gap-12 lg:grid-cols-[.7fr,1.3fr]"><Reveal variant="left"><p className="text-sm font-semibold text-[#E8432E]">{feature.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl">{feature.title}</h1><p className="mt-7 text-lg leading-8 text-white/70">{feature.intro}</p></Reveal><Reveal variant="right"><div className="grid grid-cols-2 gap-3 sm:gap-4">{feature.points.map((point,index)=><div key={point.label} className="border border-white/10 bg-white/[.04] p-5 sm:p-6"><span className="text-xs font-semibold text-[#E8432E]">0{index+1}</span><p className="mt-8 font-semibold">{point.label}</p><p className="mt-2 text-sm leading-6 text-white/60">{point.text}</p></div>)}</div></Reveal></div></div></section><section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="border-l-2 border-brand-primary/20 pl-6"><p className="max-w-3xl text-xl leading-8 text-ink-soft">{feature.summary}</p></div></section></>;
}

export function PayrollCapabilityPage({ feature }: { feature: PayrollCapability }) {
  const Icon = iconByKey[feature.variant];
  const layout = { agreement: AgreementLayout, health: HealthLayout, contributions: ContributionsLayout, netSocial: NetSocialLayout, payslip: PayslipLayout, traceability: TraceabilityLayout, profile: ProfileLayout, employer: EmployerLayout }[feature.variant];
  return <div className="min-h-screen bg-white"><MarketingHeader/><main><div className="mx-auto max-w-6xl px-6 pb-0 pt-4 sm:pt-6"><Link href="/gestion-paie" className="inline-flex items-center gap-2 text-sm text-ink-faint hover:text-ink"><ArrowRight size={14} className="rotate-180"/> Gestion de la paie</Link><div className="mt-4 flex items-center gap-2 text-xs font-medium text-ink-faint"><Icon size={14}/> {feature.eyebrow}</div></div>{layout({ feature })}<Sources feature={feature}/><section className="border-t border-surface-border"><div className="mx-auto max-w-6xl px-6 py-16 sm:py-20"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-primary">Gestion de la paie</p><p className="mt-2 text-xl font-semibold text-ink">Voir les autres traitements de paie.</p></div><Link href="/gestion-paie" className="inline-flex items-center gap-2 text-sm font-semibold text-ink hover:text-brand-primary">Retour aux sujets paie <ArrowRight size={15}/></Link></div></div></section></main><MarketingFooter/></div>;
}
