import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentMembership } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { checkPayrollPeriodReadiness } from "@/lib/payroll/period-preflight";
import PayrollVariablesSection from "../PayrollVariablesSection";
import PayrollCalculateButton from "../PayrollCalculateButton";
import PayrollReviewButton from "../PayrollReviewButton";

const MONTHS = ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];
const STATUS_LABELS: Record<string, string> = { DRAFT: "Brouillon", CALCULATED: "Calculée", REVIEW: "À contrôler", VALIDATED: "Validée", LOCKED: "Verrouillée" };
function formatEuros(cents: number | null) { if (cents === null) return "Non renseigné"; return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 2 }).format(cents / 100); }
function formatPayrollEuros(value: unknown) { if (value === null || value === undefined) return "—"; const amount = Number(value); if (!Number.isFinite(amount)) return String(value); return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount); }
function formatDecimal(value: unknown) { if (value === null || value === undefined) return "Non renseigné"; return String(value); }
function sumPayrollEuros(values: unknown[]) { const total = values.reduce<number>((sum, value) => { if (value === null || value === undefined) return sum; const amount = Number(value); return Number.isFinite(amount) ? sum + amount : sum; }, 0); return formatPayrollEuros(total); }

export default async function PayrollPeriodPage({ params }: { params: { periodId: string } }) {
  const membership = await getCurrentMembership();
  if (!membership) redirect("/dashboard");
  const period = await prisma.payrollPeriod.findFirst({ where: { id: params.periodId, organizationId: membership.organizationId } });
  if (!period) notFound();
  const periodStart = new Date(period.year, period.month - 1, 1); const periodEnd = new Date(period.year, period.month, 0); periodStart.setHours(0,0,0,0); periodEnd.setHours(23,59,59,999); const calculationDate = new Date(period.year, period.month - 1, 1, 12, 0, 0, 0);
  const [employees, profiles, calculations, variables, validatedRules] = await Promise.all([
    prisma.employee.findMany({ where: { organizationId: membership.organizationId, deletedAt: null }, select: { id:true, firstName:true,lastName:true,position:true,contractType:true }, orderBy:[{lastName:"asc"},{firstName:"asc"}] }),
    prisma.payrollProfile.findMany({ where:{ organizationId:membership.organizationId,effectiveFrom:{lte:periodEnd},OR:[{effectiveUntil:null},{effectiveUntil:{gte:periodStart}}] }, select:{employeeId:true,baseSalaryCents:true,monthlyHours:true,effectiveFrom:true}, orderBy:{effectiveFrom:"desc"} }),
    prisma.payrollCalculation.findMany({ where:{organizationId:membership.organizationId,payrollPeriodId:period.id}, select:{employeeId:true,grossAmount:true,employeeContributions:true,employerContributions:true,netBeforeTax:true,withholdingTax:true,netPaid:true} }),
    prisma.payrollVariable.findMany({ where:{organizationId:membership.organizationId,payrollPeriodId:period.id}, select:{id:true,employeeId:true,code:true,label:true,amount:true,unit:true,source:true}, orderBy:[{employeeId:"asc"},{createdAt:"asc"}] }),
    prisma.payrollRuleVersion.findMany({ where:{status:"VALIDATED",validFrom:{lte:calculationDate},OR:[{validUntil:null},{validUntil:{gte:calculationDate}}]}, select:{id:true,code:true,version:true,scope:true,sourceName:true,sourceUrl:true}, orderBy:[{code:"asc"},{scope:"asc"},{version:"desc"}] }),
  ]);
  const profileByEmployee = new Map<string,(typeof profiles)[number]>(); for (const profile of profiles) if(!profileByEmployee.has(profile.employeeId)) profileByEmployee.set(profile.employeeId,profile);
  const calculationByEmployee = new Map<string,(typeof calculations)[number]>(); for (const calculation of calculations) calculationByEmployee.set(calculation.employeeId,calculation);
  const configuredCount=employees.filter(e=>profileByEmployee.has(e.id)).length; const calculatedCount=employees.filter(e=>calculationByEmployee.has(e.id)).length; const missingProfileCount=employees.length-configuredCount;
  const readiness=checkPayrollPeriodReadiness(employees.map(e=>{const p=profileByEmployee.get(e.id);return {employeeId:e.id,firstName:e.firstName,lastName:e.lastName,baseSalaryCents:p?.baseSalaryCents,monthlyHours:p?.monthlyHours==null?null:Number(p.monthlyHours)};}));
  const variableRows=variables.map(v=>({id:v.id,employeeId:v.employeeId,code:v.code,label:v.label,amount:String(v.amount),unit:v.unit,source:v.source}));
  const calculatedRows=employees.map(e=>calculationByEmployee.get(e.id)).filter((c): c is (typeof calculations)[number]=>Boolean(c));
  const hasValidatedRule=validatedRules.length>0;
  const calculationDisabled=membership.accessRole!=="OWNER"&&membership.accessRole!=="ADMIN" ? true : period.status!=="DRAFT"||!readiness.ready||!hasValidatedRule;
  const reviewDisabled=membership.accessRole!=="OWNER"&&membership.accessRole!=="ADMIN" ? true : period.status!=="CALCULATED"||calculatedCount!==employees.length||employees.length===0;
  return (<div className="mx-auto max-w-6xl">
    <Link href="/dashboard/payroll" className="text-sm text-ink-soft hover:text-ink">← Retour à la paie</Link>
    <div className="mt-4 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-brand-primary">Période de paie</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-ink">{MONTHS[period.month-1]} {period.year}</h1><p className="mt-1 text-sm text-ink-soft">Cycle : brouillon → calculée → contrôle → validée → verrouillée.</p></div><span className="rounded-full bg-surface-subtle px-3 py-1.5 text-sm font-semibold text-ink-soft">{STATUS_LABELS[period.status]??period.status}</span></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-surface-border bg-white p-5"><p className="text-xs text-ink-faint">Salariés actifs</p><p className="mt-2 text-2xl font-semibold text-ink">{employees.length}</p></div><div className="rounded-xl border border-surface-border bg-white p-5"><p className="text-xs text-ink-faint">Profils paie disponibles</p><p className="mt-2 text-2xl font-semibold text-ink">{configuredCount}/{employees.length}</p></div><div className="rounded-xl border border-surface-border bg-white p-5"><p className="text-xs text-ink-faint">Calculs enregistrés</p><p className="mt-2 text-2xl font-semibold text-ink">{calculatedCount}/{employees.length}</p></div></div>
    {!readiness.ready ? <section className="mt-6 rounded-xl border border-accent-amber/30 bg-accent-amber/10 px-5 py-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent-amber">Préparation</p><p className="mt-1 font-semibold text-ink">Le calcul est bloqué tant que les données de base sont incomplètes.</p></div><span className="rounded-full bg-white/70 px-3 py-1.5 text-xs font-semibold text-ink-soft">{readiness.issues.length} point{readiness.issues.length>1?"s":""} à corriger</span></div><div className="mt-3 space-y-1.5 text-sm text-ink-soft">{readiness.issues.map((issue,index)=><p key={`${issue.code}-${issue.employeeId??"period"}-${index}`}>• {issue.message}</p>)}</div></section> : <section className="mt-6 rounded-xl border border-accent-teal/30 bg-accent-teal/10 px-5 py-4"><p className="text-xs font-semibold uppercase tracking-wider text-accent-teal">Préparation</p><p className="mt-1 font-semibold text-ink">Les données salarié de base sont prêtes pour l’étape de calcul.</p><p className="mt-1 text-sm text-ink-soft">Cela ne signifie pas encore que les règles légales et conventionnelles nécessaires sont disponibles et validées.</p></section>}
    <section className="mt-7 rounded-xl border border-surface-border bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-semibold text-ink">Règle de paie applicable</h2><p className="mt-1 text-sm text-ink-soft">Le calcul ne peut démarrer qu’avec une version de règle validée et applicable à la période.</p></div><span className="rounded-full bg-surface-subtle px-3 py-1.5 text-xs font-semibold text-ink-soft">{validatedRules.length} version{validatedRules.length>1?"s":""} disponible{validatedRules.length>1?"s":""}</span></div>{hasValidatedRule ? <PayrollCalculateButton periodId={period.id} disabled={calculationDisabled} ruleCode={validatedRules[0].code} ruleScope={validatedRules[0].scope}/> : <p className="mt-4 rounded-lg bg-accent-amber/10 px-3 py-2 text-sm text-accent-amber">Aucune version de règle de paie validée n’est disponible pour cette période.</p>}</section>
    {calculatedRows.length>0 ? <section className="mt-7 rounded-xl border border-surface-border bg-white p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent-teal">Résultat enregistré</p><h2 className="mt-1 text-lg font-semibold text-ink">Synthèse du calcul de paie</h2><p className="mt-1 text-sm text-ink-soft">Cette synthèse reprend uniquement les montants enregistrés par le moteur de paie pour cette période.</p></div><span className="rounded-full bg-accent-teal/10 px-3 py-1.5 text-xs font-semibold text-accent-teal">{calculatedRows.length}/{employees.length} salarié{calculatedRows.length>1?"s":""} calculé{calculatedRows.length>1?"s":""}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Brut total",sumPayrollEuros(calculatedRows.map(c=>c.grossAmount))],["Cotisations salariales",sumPayrollEuros(calculatedRows.map(c=>c.employeeContributions))],["Net avant impôt",sumPayrollEuros(calculatedRows.map(c=>c.netBeforeTax))],["PAS",sumPayrollEuros(calculatedRows.map(c=>c.withholdingTax))],["Net payé",sumPayrollEuros(calculatedRows.map(c=>c.netPaid))]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-surface-border bg-surface-subtle/40 p-4"><p className="text-xs text-ink-faint">{label}</p><p className="mt-1 text-lg font-semibold text-ink">{value}</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="min-w-[1180px] w-full text-sm"><thead><tr className="border-b border-surface-border bg-surface-subtle/50 text-left text-xs font-semibold text-ink-faint"><th className="px-4 py-3">Salarié</th><th className="px-4 py-3">Brut</th><th className="px-4 py-3">Cotisations salariales</th><th className="px-4 py-3">Cotisations employeur</th><th className="px-4 py-3">Net avant impôt</th><th className="px-4 py-3">PAS</th><th className="px-4 py-3">Net payé</th></tr></thead><tbody className="divide-y divide-surface-border">{employees.map(e=>{const c=calculationByEmployee.get(e.id);if(!c)return null;return <tr key={e.id}><td className="px-4 py-4"><p className="font-medium text-ink">{e.firstName} {e.lastName}</p><p className="mt-0.5 text-xs text-ink-faint">{e.position||"Poste non renseigné"}</p></td><td className="px-4 py-4 font-medium text-ink">{formatPayrollEuros(c.grossAmount)}</td><td className="px-4 py-4 text-ink-soft">{formatPayrollEuros(c.employeeContributions)}</td><td className="px-4 py-4 text-ink-soft">{formatPayrollEuros(c.employerContributions)}</td><td className="px-4 py-4 font-medium text-ink">{formatPayrollEuros(c.netBeforeTax)}</td><td className="px-4 py-4 text-ink-soft">{formatPayrollEuros(c.withholdingTax)}</td><td className="px-4 py-4 font-semibold text-ink">{formatPayrollEuros(c.netPaid)}</td></tr>})}</tbody></table></div></section>:null}
    {period.status==="CALCULATED" ? <PayrollReviewButton periodId={period.id} disabled={reviewDisabled}/> : null}
    <section className="mt-7 overflow-hidden rounded-xl border border-surface-border bg-white"><div className="border-b border-surface-border px-5 py-4"><h2 className="font-semibold text-ink">Salariés de la période</h2><p className="mt-1 text-xs text-ink-faint">Cette vue prépare le contrôle de paie. Aucun calcul n&apos;est inventé lorsqu&apos;une donnée réglementaire ou salarié manque.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr className="border-b border-surface-border bg-surface-subtle/50 text-left text-xs font-semibold text-ink-faint"><th className="px-5 py-3">Salarié</th><th className="px-5 py-3">Contrat</th><th className="px-5 py-3">Brut de référence</th><th className="px-5 py-3">Heures</th><th className="px-5 py-3">Calcul</th><th className="px-5 py-3">Net avant impôt</th></tr></thead><tbody className="divide-y divide-surface-border">{employees.map(e=>{const p=profileByEmployee.get(e.id);const c=calculationByEmployee.get(e.id);return <tr key={e.id}><td className="px-5 py-4"><p className="font-medium text-ink">{e.firstName} {e.lastName}</p><p className="mt-0.5 text-xs text-ink-faint">{e.position||"Poste non renseigné"}</p></td><td className="px-5 py-4 text-ink-soft">{e.contractType??"Non renseigné"}</td><td className="px-5 py-4 text-ink-soft">{formatEuros(p?.baseSalaryCents??null)}</td><td className="px-5 py-4 text-ink-soft">{formatDecimal(p?.monthlyHours)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c?"bg-accent-teal/10 text-accent-teal":"bg-surface-subtle text-ink-faint"}`}>{c?"Disponible":"À calculer"}</span></td><td className="px-5 py-4 font-medium text-ink">{c?.netBeforeTax!==null&&c?.netBeforeTax!==undefined?formatPayrollEuros(c.netBeforeTax):"—"}</td></tr>})}</tbody></table></div></section>
    <PayrollVariablesSection periodId={period.id} employees={employees.map(e=>({id:e.id,firstName:e.firstName,lastName:e.lastName}))} variables={variableRows} readOnly={membership.accessRole!=="OWNER"&&membership.accessRole!=="ADMIN"}/>
    <section className="mt-7 rounded-xl border border-surface-border bg-white p-5"><h2 className="font-semibold text-ink">Contrôles</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-surface-border bg-surface-subtle/40 p-4"><p className="text-xs text-ink-faint">Profils manquants</p><p className="mt-1 text-lg font-semibold text-ink">{missingProfileCount}</p></div><div className="rounded-lg border border-surface-border bg-surface-subtle/40 p-4"><p className="text-xs text-ink-faint">Calculs manquants</p><p className="mt-1 text-lg font-semibold text-ink">{employees.length-calculatedCount}</p></div><div className="rounded-lg border border-surface-border bg-surface-subtle/40 p-4"><p className="text-xs text-ink-faint">Étape suivante</p><p className="mt-1 text-sm font-semibold text-ink">{!readiness.ready?"Compléter les données de base":!hasValidatedRule?"Publier une règle de paie validée":variables.length===0?"Saisir les variables":calculatedCount<employees.length?"Contrôler les calculs manquants":period.status==="CALCULATED"?"Passer au contrôle de la période":"Continuer le cycle de paie"}</p></div></div></section>
  </div>);
}