import Link from "next/link";
import { LegalDocument } from "@/components/landing/LegalDocument";
import { LEGAL_VERSIONS } from "@/lib/legalVersions";
export const metadata = { title: "Conditions générales de vente", description: "Abonnement professionnel RH Pilot : prix, paiement, durée, résiliation et assistance." };
export default function Page() { return <LegalDocument title="Conditions générales de vente" version={LEGAL_VERSIONS.cgv.label}>
<section><h2>1. Parties et documents contractuels</h2><p>Le service est fourni par Aimen EL HOUSSEINI, entrepreneur individuel exerçant sous le nom RH Pilot, 198 rue Robert Koch, 34090 Montpellier, RCS Montpellier 108 345 125. Contact : contact@rhpilot.fr. Le client est une organisation agissant pour ses besoins professionnels. La personne qui souscrit déclare être autorisée à engager cette organisation.</p><p>Le contrat comprend les présentes CGV, les <Link href="/cgu">CGU</Link>, le <Link href="/dpa">contrat de sous-traitance des données</Link> et le récapitulatif de commande Stripe. Le récapitulatif prévaut sur les conditions générales pour le prix effectivement commandé.</p></section>
<section><h2>2. Service et accès anticipé à la paie</h2><p>Le plan Gratuit permet le suivi de trois salariés réels actifs. Pro lève cette limite et comprend les parcours RH, les rappels, le Copilote et l’espace salarié. Les comptes salariés et les fiches de démonstration ne sont pas facturés.</p><p>Le calcul de paie est un accès anticipé, sur invitation distincte. Souscrire Pro ne l’active pas. Les cas pris en charge sont limités ; les bulletins doivent être vérifiés avant remise. La préparation DSN ne comprend ni dépôt sur net-entreprises ni garantie d’acceptation. Les bulletins externes peuvent être déposés dans l’espace salarié sans accès au moteur de paie.</p></section>
<section><h2>3. Prix et paiement</h2><p>Pro coûte 15 € HT par mois, plus 3 € HT par salarié réel actif suivi. TVA non applicable, article 293 B du CGI. L’effectif facturable est indiqué dans Facturation et synchronisé avec Stripe. Le montant et la périodicité sont affichés avant paiement ; le client peut corriger son effectif avant de commander.</p><p>Le paiement récurrent est assuré par Stripe. Le client accepte les documents contractuels avant d’être redirigé vers le paiement. Le paiement confirmé active l’abonnement. Les factures sont consultables dans Facturation et dans le portail Stripe. Un incident de paiement est signalé au client ; les données ne sont pas supprimées du seul fait de cet incident.</p><p>Les sommes sont payables à la date d’échéance indiquée par Stripe. Aucun escompte n’est accordé pour paiement anticipé. Tout retard de paiement entraîne de plein droit, sans rappel préalable, des pénalités de retard au taux d’intérêt appliqué par la Banque centrale européenne à son opération de refinancement la plus récente, majoré de 10 points, ainsi qu’une indemnité forfaitaire pour frais de recouvrement de 40 € (articles L441-10 et D441-5 du Code de commerce).</p></section>
<section><h2>4. Durée, résiliation et évolution des prix</h2><p>L’abonnement est mensuel et renouvelé automatiquement. Le client peut le résilier depuis le portail de facturation avant le prochain renouvellement. La résiliation prend effet à la fin de la période payée, sans nouvelle échéance ; une période commencée reste due, sauf erreur de facturation ou disposition impérative contraire.</p><p>Tout changement de prix est communiqué au moins trente jours avant son application à un renouvellement. Le client peut résilier avant cette date. Une modification n’est pas appliquée rétroactivement à une période payée.</p></section>
<section><h2>5. Assistance et disponibilité</h2><p>Les demandes sont adressées à contact@rhpilot.fr. RH Pilot corrige les défauts signalés et informe le client des interruptions nécessaires à la maintenance. Aucun délai garanti d’intervention ni taux contractuel de disponibilité n’est inclus dans l’offre standard.</p></section>
<section><h2>6. Responsabilités</h2><p>RH Pilot est tenu d’une obligation de moyens pour fournir le service et protéger les données conformément au contrat de sous-traitance. Le client renseigne des données exactes, configure les accès, contrôle les documents et respecte ses obligations d’employeur. Le Copilote apporte une aide et ses réponses doivent être vérifiées.</p><p>Chaque partie répond des dommages directs causés par ses manquements prouvés. Aucune clause ne supprime les obligations légales de protection des données ou la responsabilité pour faute lourde ou dolosive.</p></section>
<section><h2>7. Données à la fin du contrat</h2><p>Le client peut exporter les données et télécharger les documents avant de quitter le service. La restitution et la suppression sur instruction sont organisées selon le contrat de sous-traitance, avec traitement distinct des documents soumis à une obligation de conservation. Les documents déjà remis restent accessibles aux salariés dans les conditions des CGU.</p></section>
<section><h2>8. Droit applicable et différends</h2><p>Le contrat est soumis au droit français. En cas de différend, les parties recherchent une solution amiable par écrit avant de saisir la juridiction compétente selon les règles de droit commun.</p></section>
</LegalDocument>; }
